services:
  - type: web
    name: movies-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELEPHANTSQL_URL
        fromDatabase:
          name: movies-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: movies-db
    plan: free
